export type ModelId =
  | 'pythagorean'
  | 'chaldean'
  | 'gematria'
  | 'gates-231'
  | 'vedic'
  | 'lo-shu'

export type NumberKind =
  | 'expression'
  | 'motivation'
  | 'impression'
  | 'key-number'
  | 'life-path'
  | 'psychic'
  | 'mission'
  | 'karmic-lessons'
  | 'hidden-tendencies'
  | 'subconscious'
  | 'life-cycles'
  | 'pinnacles'
  | 'challenges'
  | 'personal-year'
  | 'personal-month'
  | 'personal-day'
  | 'union-destiny'
  | 'union-soul'
  | 'union-expression'
  | 'union-personality'
  | 'union-mission'
  | 'union-key'
  | 'brand-harmony'
  | 'founder-affinity'
  | 'marriage-governing'
  | 'marriage-personal-year'

export type SubjectKind =
  | 'person'
  | 'couple'
  | 'marriage'
  | 'company'
  | 'alternative-name'
  | 'event'
